local Scene       = require "core.modules.scenes"
local BoostLevel = Scene:extend()
local Controller = require "scenes.subgame.sonic-boost.controller"

function BoostLevel:new()
  self.controller = Controller()
  print("battle started")
  --self.background = love.graphics.newImage("assets/background/testbackground.png")
end

function BoostLevel:update(dt)
  game:update(dt)
  game.input:update(dt)
  self.controller:update(dt)
end

function BoostLevel:draw()
  --CScreen:apply()
  love.graphics.setColor(1, 1, 1, 1)
  love.graphics.rectangle("fill", 0, 0, 424, 240)
  --love.graphics.draw(self.background, 0, 0)
  self.controller:draw()
  --CScreen:cease()
end

function BoostLevel:leave()
  self.controller:destroy()
  self.controller = nil

  collectgarbage()
end

return BoostLevel
